@echo off
echo Starting AstraMark AI Platform...

echo Starting Backend Server (Enhanced)...
start "AstraMark Backend" cmd /k "cd backend && python server_enhanced.py"

echo Waiting for backend to initialize...
timeout /t 5

echo Starting Frontend...
cd frontend
npm start
